var annotated =
[
    [ "IApertureInterface", "class_i_aperture_interface.html", "class_i_aperture_interface" ],
    [ "IASDInterface", "class_i_a_s_d_interface.html", "class_i_a_s_d_interface" ],
    [ "IASDInterface2", "class_i_a_s_d_interface2.html", "class_i_a_s_d_interface2" ],
    [ "IASDInterface3", "class_i_a_s_d_interface3.html", "class_i_a_s_d_interface3" ],
    [ "IASDLoader", "class_i_a_s_d_loader.html", "class_i_a_s_d_loader" ],
    [ "ICameraPortMirrorInterface", "class_i_camera_port_mirror_interface.html", "class_i_camera_port_mirror_interface" ],
    [ "IConfocalModeInterface", "class_i_confocal_mode_interface.html", "class_i_confocal_mode_interface" ],
    [ "IConfocalModeInterface2", "class_i_confocal_mode_interface2.html", "class_i_confocal_mode_interface2" ],
    [ "IConfocalModeInterface3", "class_i_confocal_mode_interface3.html", "class_i_confocal_mode_interface3" ],
    [ "IDichroicMirrorInterface", "class_i_dichroic_mirror_interface.html", "class_i_dichroic_mirror_interface" ],
    [ "IDiskInterface", "class_i_disk_interface.html", "class_i_disk_interface" ],
    [ "IDiskInterface2", "class_i_disk_interface2.html", "class_i_disk_interface2" ],
    [ "IEmissionIrisInterface", "class_i_emission_iris_interface.html", "class_i_emission_iris_interface" ],
    [ "IEPIPolariserInterface", "class_i_e_p_i_polariser_interface.html", "class_i_e_p_i_polariser_interface" ],
    [ "IFilterConfigInterface", "class_i_filter_config_interface.html", "class_i_filter_config_interface" ],
    [ "IFilterRepository", "class_i_filter_repository.html", "class_i_filter_repository" ],
    [ "IFilterSet", "class_i_filter_set.html", "class_i_filter_set" ],
    [ "IFilterWheelInterface", "class_i_filter_wheel_interface.html", "class_i_filter_wheel_interface" ],
    [ "IFilterWheelModeInterface", "class_i_filter_wheel_mode_interface.html", "class_i_filter_wheel_mode_interface" ],
    [ "IFilterWheelSpeedInterface", "class_i_filter_wheel_speed_interface.html", "class_i_filter_wheel_speed_interface" ],
    [ "IFrontPanelLEDInterface", "class_i_front_panel_l_e_d_interface.html", "class_i_front_panel_l_e_d_interface" ],
    [ "IIllLensInterface", "class_i_ill_lens_interface.html", "class_i_ill_lens_interface" ],
    [ "ILensInterface", "class_i_lens_interface.html", "class_i_lens_interface" ],
    [ "INDFilterInterface", "class_i_n_d_filter_interface.html", "class_i_n_d_filter_interface" ],
    [ "INotify", "class_i_notify.html", "class_i_notify" ],
    [ "IRestrictionInterface", "class_i_restriction_interface.html", "class_i_restriction_interface" ],
    [ "IShutterInterface", "class_i_shutter_interface.html", "class_i_shutter_interface" ],
    [ "IStatusInterface", "class_i_status_interface.html", "class_i_status_interface" ],
    [ "ISuperResInterface", "class_i_super_res_interface.html", "class_i_super_res_interface" ],
    [ "ITIRFInterface", "class_i_t_i_r_f_interface.html", "class_i_t_i_r_f_interface" ],
    [ "ITIRFPolariserInterface", "class_i_t_i_r_f_polariser_interface.html", "class_i_t_i_r_f_polariser_interface" ]
];